Feat@display all beer
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-100_pressions pull request #2
Opened 2023-10-27 10:18 UTC by Romeoseb-dev

2023-10-27 10:21 UTC, valihna approved these changes

2023-11-07 10:18 UTC, jujuck requested changes

2023-11-07 10:18 UTC, jujuck commented on frontend/src/App.jsx
> +      .get("http://localhost:3310/api/beers")
Mettre la requete dans le loader du main.jsx

2023-11-07 10:18 UTC, jujuck commented on frontend/src/App.jsx
> +        afficher toutes les bières
Afficher les bières et faire le css complet

2023-11-09 15:34 UTC, OlvMrn approved these changes

2023-11-09 16:06 UTC, jujuck requested changes

2023-11-09 16:06 UTC, jujuck commented on frontend/src/App.jsx
> +  const [beers, setBeers] = useState([]);
On va mettre la requete dans la loader de la route. On ne fait pas de requete en direct dans un composant ou page react. Cela génére des boucles difficiles à maitriser et des pb de chargement. Donc requete dans main.jsx

2023-11-09 16:06 UTC, jujuck commented on frontend/src/components/BeerList.jsx
> +    <div className="beer-list">
Mettre la className beer-list dans un fichier séparé BeerList.css

2023-11-09 16:06 UTC, jujuck commented on frontend/src/components/BeerCard.jsx
> +
Mettre tout le style relatif à ta carte Biere dans un fichier spécifique BeerCard.css

2023-11-09 16:06 UTC, jujuck commented on frontend/src/components/BeerCard.jsx
> +
Sauf les classes partagées (beer-item ${beer.type.toLowerCase()}-color) cf Olivier

2023-11-09 16:06 UTC, jujuck commented on frontend/src/App.css
> +* {
Couper ton Css en différents fichiers plus spécifique. On ne gardera ici que le style global et partagé dans l'app

2023-11-10 09:28 UTC, OlvMrn approved these changes

2023-11-10 09:39 UTC, jujuck requested changes

2023-11-10 09:39 UTC, jujuck commented on frontend/src/components/BeerCard.css
> +.title {
A deplacer

2023-11-10 09:41 UTC, jujuck requested changes

2023-11-10 09:41 UTC, jujuck commented on frontend/src/main.jsx
> +      return axios.get("http://localhost:3310/api/beers").then((response) => {
Remplacer http://localhost:3310 par ${import.meta.env.VITE_BACKEND_URL}

2023-11-10 10:01 UTC, OlvMrn approved these changes

2023-11-10 10:11 UTC, OlvMrn approved these changes

2023-11-10 10:21 UTC, jujuck approved these changes

2023-11-10 10:26 UTC, merged