Ajout de la route pour afficher 1 bière, affichage dans la console du…
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-100_pressions pull request #3
Opened 2023-10-27 10:24 UTC by OlvMrn

… navigateur via un bouton

2023-10-27 10:25 UTC, Romeoseb-dev approved these changes

2023-11-07 10:22 UTC, jujuck requested changes

2023-11-07 10:22 UTC, jujuck commented on frontend/src/App.jsx
> +      .get(`http://localhost:3310/api/beers/${id}`)
Loader à ajouter dans la main.jsx, créer une page composant tout de suite

2023-11-07 10:22 UTC, jujuck commented on frontend/src/App.jsx
>          console.info(items.data);
Pas de console.info,.... Faire l'affichage de la bière avec ses détails

2023-11-08 14:17 UTC, valihna approved these changes

2023-11-08 14:23 UTC, Romeoseb-dev approved these changes

2023-11-09 10:06 UTC, jujuck requested changes

2023-11-09 10:06 UTC, jujuck commented on frontend/src/components/BeerInfo.css
> +:root {
Si c'est root, alors c'est pour toute l'app.. Donc dans app.css ou index.css (Choix d'équipe). On ne va mettre dans BeerInfo.css, que le css spécifique à cette page

2023-11-09 10:06 UTC, jujuck commented on frontend/src/components/BeerInfo.css
> +* {
Si c'est *, alors c'est pour toute l'app.. Donc dans app.css ou index.css (Choix d'équipe). On ne va mettre dans BeerInfo.css, que le css spécifique à cette page

2023-11-09 10:06 UTC, jujuck commented on frontend/src/components/BeerInfo.css
> +body {
Si c'est body, alors c'est pour toute l'app.. Donc dans app.css ou index.css (Choix d'équipe). On ne va mettre dans BeerInfo.css, que le css spécifique à cette page

2023-11-09 10:06 UTC, jujuck commented on frontend/src/components/BeerInfo.css
> +.bg-IPA {
Si c'est .bg-IPA et etc, alors c'est pour toute l'app.. Donc dans app.css ou index.css (Choix d'équipe). On ne va mettre dans BeerInfo.css, que le css spécifique à cette page

2023-11-09 10:06 UTC, jujuck commented on frontend/src/components/BeerInfo.jsx
> +          <div className="beer-info-content">
Tu peux mettre un composant en place étant donné que chaque section est relativement identique
<div className="beer-info-content">
            <div className="beer-info-content-header">Description:</div>
            <div className="beer-info-content-value">
              {selectedBeer.description}
            </div>
          </div>

2023-11-09 10:06 UTC, jujuck commented on frontend/src/main.jsx
> +        .get(`http://localhost:3310/api/beers/${params.id}`)
on va mettre http://localhost:3310 en dynamique via la variable d'environnement ${import.meta.enc.VITE_BACKEND_URL}

2023-11-09 15:32 UTC, Romeoseb-dev approved these changes

2023-11-09 15:54 UTC, jujuck approved these changes

2023-11-09 15:54 UTC, merged