Feat@sidebar
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-100_pressions pull request #6
Opened 2023-11-15 14:31 UTC by Romeoseb-dev

2023-11-15 14:32 UTC, valihna approved these changes

2023-11-15 14:46 UTC, OlvMrn approved these changes

2023-11-15 16:03 UTC, aimach requested changes

2023-11-15 16:03 UTC, aimach commented on frontend/src/components/SideBar.css
> +h3 {
Attention à l'application de style sur des balises html ! 
Si ce style concerne tous les h3, le passer dans un fichier index.css qui sera appelé dans main.jsx (plus haut niveau). 
Si ça ne concerne que la sidebar, mettre une classe.

2023-11-16 14:35 UTC, aimach approved these changes

2023-11-16 14:35 UTC, merged