Feat@favorite
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-100_pressions pull request #7
Opened 2023-11-16 11:03 UTC by OlvMrn

2023-11-16 11:08 UTC, valihna approved these changes

2023-11-16 14:36 UTC, aimach commented
La validation de la PR#6 a créé des conflits qu'il faut résodure (sur BeerCard.jsx)

2023-11-16 14:51 UTC, aimach requested changes
Il faut harmoniser vos noms de classe entre l'utilisation de (-) ou (_).
Sinon, bravo pour le context !!

2023-11-16 14:51 UTC, aimach commented on frontend/src/components/FavButton.css
> +button {
attention, ne pas appliquer de style sur des balises directement, sauf dans index.css
il vaut mieux mettre une classe

2023-11-17 07:26 UTC, jujuck requested changes, later dismissed

2023-11-17 07:26 UTC, jujuck commented on frontend/src/components/FavButton.jsx
> +      {isFavorite ? <AiFillHeart /> : <AiOutlineHeart />}
Mettre directement le favorites.includes(beerId) ici dans le return. La création de variable est inutile car celle-ci n'est utilisé q'une seule fois

2023-11-17 07:26 UTC, jujuck commented on frontend/src/components/FilterOption.jsx
> +/* import "./Types.css"; */
PAs de code mort

2023-11-17 07:26 UTC, jujuck commented on frontend/src/components/BeerCard.jsx
> +import "./BeerCard.css";
Mettre l'import de css en dernier (D'abord les import de libraires, puis les pages/composant)

2023-11-17 08:35 UTC, aimach approved these changes

2023-11-17 08:36 UTC, merged