Feat@basket cart
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-100_pressions pull request #8
Opened 2023-11-16 11:37 UTC by valihna

Mise en place du backend frontend de la page panier

2023-11-16 13:39 UTC, Romeoseb-dev approved these changes

2023-11-16 15:08 UTC, jujuck requested changes

2023-11-16 15:08 UTC, jujuck commented on frontend/src/components/BasketCart.css
> +.Panier {
Remplacer le nom de la class css par basket sans majuscule pour uniformiser

2023-11-16 15:08 UTC, jujuck commented on frontend/src/components/BasketCart.jsx
> +            <p className="sous-total">Sous-total</p>
Attention au franglais dans les class CSS

2023-11-16 15:08 UTC, jujuck commented on frontend/src/components/BasketCart.jsx
> +// Mettre en place un useEffect pour charger en automatique les données relatives au bière
Supprimer le code mort

2023-11-16 15:08 UTC, jujuck commented on frontend/src/components/Button.jsx
> +      {/* <button onClick={handleClick}></button> */}
Suppression du code mort

2023-11-17 07:17 UTC, jujuck approved these changes

2023-11-17 07:17 UTC, merged